### ISSUE TITLE
Potential Bug: GPS Map Markers Missing

### ISSUE THREAD

**Issue by JamesTheClarke** [freghar/arma-additions#2]
I'm not sure if this is intentional but if it is feel free to close this issue.

When opening GPS mini-window the Freghar map markers do not show up. They are visible on the regular map but completely invisible on the mini GPS which can make on the fly coordination difficult.

**Comment by freghar** [comment]
This is not intentional. I already hook up quite a few places (https://github.com/freghar/arma-additions/blob/bf1af6c2baa/addons/map_trackers/fn_hookAnyMapDisplay.sqf#L22 + curator map separately via DisplayLoad XEH), but not GPS minimap. Not sure if it's even possible, but will give it a shot.

**Comment by freghar** [comment]
(for my future reference)

The GPS doesn't show up in `allDisplays`, but does actually exist as a valid Display found via `uiNamespace` with idd of 311, or `IDD_CUSTOMINFO_MINIMAP`. Looking into its config, it defines several Controls and idc 13301 seems to be some kind of MiniMap, so it might behave like display 12 control 51 (normal map).
TODO: See if it's possible to draw on it via the Draw EH.

**Comment by freghar** [comment]
So this should be fixed with https://github.com/freghar/arma-additions/commit/9d5716a6165f82fb9d97a63db90e50978ea7530d and https://github.com/freghar/arma-additions/commit/999fa0f6b2dc78ae6f0f9bae7fdb26db5095d768 .

Unfortunately, it's not so easy to parametrize which trackers to show (none, only group, only soldier, both) on the GPS as I essentially just hook any and all Displays and then share the drawing function for all. And while I could do some heavy rewrites of [the drawing function](https://github.com/freghar/arma-additions/blob/999fa0f6b2dc78ae6f0f9bae7fdb26db5095d768/addons/map_trackers/fn_setupDrawEH.sqf) , splitting off the pieces into separate functions + parametrizing their calling by Display type (`ctrlIDD`), ... that's maybe something for the future.

For now, the GPS is unfortunately going to display exactly what the main map has - both soldier and group trackers (if both are configured to show on the main map), sort of duplicating sthud functionality.
